In [45]:
import  torch

## 加法add;add_

In [46]:
a = torch.tensor([1.])
b = torch.tensor([2.])
print(a + b)
print(a.add(b))
print(a)

tensor([3.])
tensor([3.])
tensor([1.])


In [47]:
a.add_(b) # In-place version of add()
print(a)

tensor([3.])


## 减法sub/sub_

## 乘法mul/mul_

In [48]:
a = torch.tensor([1.])
b = torch.tensor([2.])
print(a * b)
print(a.mul(b))
print(a)

tensor([2.])
tensor([2.])
tensor([1.])


In [49]:
a.mul_(b) # In-place version of mul()
print(a)

tensor([2.])


## 除法div/div_

## 地板除法

In [50]:
a = torch.tensor([4.0, 3.0])
b = torch.tensor([2.0, 2.0])
print(a//b)

tensor([2., 1.])


# 余数

In [51]:
a % b

tensor([0., 1.])

In [52]:
a > b

tensor([True, True])

In [53]:
print(a == b)
print(a.eq(b)) # 与上等价

tensor([False, False])
tensor([False, False])


In [54]:
a.equal(b) # 所有元素是否相等;等价于torch.all(a.eq(b))

False