In [17]:
import  torch

## 加法add;add_

In [18]:
a = torch.tensor([1.])
b = torch.tensor([2.])
print(a + b)
print(a.add(b))
print(a)

tensor([3.])
tensor([3.])
tensor([1.])


In [19]:
a.add_(b) # In-place version of add()
print(a)

tensor([3.])


## 减法sub/sub_

## 乘法mul/mul_

In [20]:
a = torch.tensor([1.])
b = torch.tensor([2.])
print(a * b)
print(a.mul(b))
print(a)

tensor([2.])
tensor([2.])
tensor([1.])


In [21]:
a.mul_(b) # In-place version of mul()
print(a)

tensor([2.])


## 除法div/div_

In [22]:
a = torch.tensor([-5, 5, 7, 9, -13])
b = torch.tensor([2, 3, 4, 2, 4])
torch.div(a.to(torch.float32), b.to(torch.float32)) # 真正的除法(指定数据类型为浮点型)

tensor([-2.5000,  1.6667,  1.7500,  4.5000, -3.2500])

In [23]:
not_div = a / b # 若a,b均为整型,则a/b是对真正的除法进行去尾操作后的结果
print(not_div.dtype) # 仍为整型
print(not_div)

torch.int64
tensor([-2,  1,  1,  4, -3])


In [24]:
a % b # 取余(必大于0)

tensor([1, 2, 3, 1, 3])

In [25]:
print(a > b)
print(a.ge(b)) # 与上等价

tensor([False,  True,  True,  True, False])
tensor([False,  True,  True,  True, False])


In [26]:
print(a < b)
print(a.le(b)) # 与上等价

tensor([ True, False, False, False,  True])
tensor([ True, False, False, False,  True])


In [27]:
print(a == b)
print(a.eq(b)) # 与上等价

tensor([False, False, False, False, False])
tensor([False, False, False, False, False])


In [28]:
a.equal(b) # 所有元素是否相等;等价于torch.all(a.eq(b))

False