Clamp all elements in input into the range [ min, max ] and return a resulting tensor:

\begin{equation}
y_i=\begin{cases}
	    \min, & \text{if} \quad  x < \min \\
        x_i, & \text{if} \quad  \min< x < \max \\
        \max, & \text{if} \quad x> \max
     \end{cases}
\end{equation}

In [34]:
import torch

grad = torch.rand(4, 4) * 15
print(grad.max())
print(grad.min())

tensor(13.5232)
tensor(0.1868)


In [35]:
grad

tensor([[ 1.8949,  0.1868, 13.5232,  8.1351],
        [ 5.8502,  4.3816,  6.4179,  4.5749],
        [ 1.5041,  7.5595,  3.2816,  7.1943],
        [ 8.9029, 12.0819,  7.5199, 13.1309]])

In [36]:
grad.clamp(min=6)

tensor([[ 6.0000,  6.0000, 13.5232,  8.1351],
        [ 6.0000,  6.0000,  6.4179,  6.0000],
        [ 6.0000,  7.5595,  6.0000,  7.1943],
        [ 8.9029, 12.0819,  7.5199, 13.1309]])

In [37]:
grad.clamp(max=6)

tensor([[1.8949, 0.1868, 6.0000, 6.0000],
        [5.8502, 4.3816, 6.0000, 4.5749],
        [1.5041, 6.0000, 3.2816, 6.0000],
        [6.0000, 6.0000, 6.0000, 6.0000]])

In [38]:
grad.clamp(min=6, max=7) #

tensor([[6.0000, 6.0000, 7.0000, 7.0000],
        [6.0000, 6.0000, 6.4179, 6.0000],
        [6.0000, 7.0000, 6.0000, 7.0000],
        [7.0000, 7.0000, 7.0000, 7.0000]])