In [28]:
import  numpy as np

arr_mul = np.random.randn(5, 7, 4)
arr_mul

array([[[ 3.55034072e-01, -4.34122071e-02, -1.06959704e+00,
          1.05099657e+00],
        [ 1.16312717e+00, -2.20173660e+00, -1.12964019e+00,
         -2.88009890e-01],
        [ 4.17195395e-01,  1.61472707e-01,  8.85039430e-01,
         -5.23143335e-04],
        [ 4.51137733e-01,  2.10636996e+00,  5.23348067e-01,
         -1.01610105e+00],
        [-6.98677186e-01,  9.67172655e-01,  2.73299899e-01,
         -1.05498607e+00],
        [ 2.11753986e+00,  1.27201465e-02, -5.04733390e-01,
          1.86486968e+00],
        [-1.85567022e-01, -9.75778964e-01,  8.12798270e-01,
          3.11920734e-01]],

       [[ 1.17537333e+00, -1.63869449e+00,  1.89006094e+00,
         -1.90127816e-01],
        [-1.13560025e+00,  1.62503986e+00, -1.29290909e+00,
          3.11349295e+00],
        [ 1.09908101e+00,  4.54185328e-01,  8.56930792e-01,
         -2.65200711e-01],
        [ 4.94642894e-01,  4.89948110e-01,  8.31117987e-01,
         -1.66498496e+00],
        [-4.04611676e-01, -6.95302116e-01

In [29]:
arr_mul[0, 1, 1] # 索引标量数值

-2.2017366019948255

In [30]:
arr_mul[0] # 从第零个维度开始索引/切片(DataFrame从列开始进行索引切片)

array([[ 3.55034072e-01, -4.34122071e-02, -1.06959704e+00,
         1.05099657e+00],
       [ 1.16312717e+00, -2.20173660e+00, -1.12964019e+00,
        -2.88009890e-01],
       [ 4.17195395e-01,  1.61472707e-01,  8.85039430e-01,
        -5.23143335e-04],
       [ 4.51137733e-01,  2.10636996e+00,  5.23348067e-01,
        -1.01610105e+00],
       [-6.98677186e-01,  9.67172655e-01,  2.73299899e-01,
        -1.05498607e+00],
       [ 2.11753986e+00,  1.27201465e-02, -5.04733390e-01,
         1.86486968e+00],
       [-1.85567022e-01, -9.75778964e-01,  8.12798270e-01,
         3.11920734e-01]])

In [31]:
arr_mul[0, 0, -1] # 索引,若为标量则返回具体数值(且支持负数索引)

1.050996568948269

In [32]:
arr_mul[0:2] # 切片,返回array

array([[[ 3.55034072e-01, -4.34122071e-02, -1.06959704e+00,
          1.05099657e+00],
        [ 1.16312717e+00, -2.20173660e+00, -1.12964019e+00,
         -2.88009890e-01],
        [ 4.17195395e-01,  1.61472707e-01,  8.85039430e-01,
         -5.23143335e-04],
        [ 4.51137733e-01,  2.10636996e+00,  5.23348067e-01,
         -1.01610105e+00],
        [-6.98677186e-01,  9.67172655e-01,  2.73299899e-01,
         -1.05498607e+00],
        [ 2.11753986e+00,  1.27201465e-02, -5.04733390e-01,
          1.86486968e+00],
        [-1.85567022e-01, -9.75778964e-01,  8.12798270e-01,
          3.11920734e-01]],

       [[ 1.17537333e+00, -1.63869449e+00,  1.89006094e+00,
         -1.90127816e-01],
        [-1.13560025e+00,  1.62503986e+00, -1.29290909e+00,
          3.11349295e+00],
        [ 1.09908101e+00,  4.54185328e-01,  8.56930792e-01,
         -2.65200711e-01],
        [ 4.94642894e-01,  4.89948110e-01,  8.31117987e-01,
         -1.66498496e+00],
        [-4.04611676e-01, -6.95302116e-01

In [33]:
arr_mul[0:2, 0:3, 0] # 在多个维度上索引/切片

array([[ 0.35503407,  1.16312717,  0.41719539],
       [ 1.17537333, -1.13560025,  1.09908101]])

In [34]:
arr_mul[0:2, 0:6:2, 2] # 第一个维度上的切片步长为2(最后一步若小于步长,则丢弃),切片范围为0-6

array([[-1.06959704,  0.88503943,  0.2732999 ],
       [ 1.89006094,  0.85693079, -1.31839142]])

In [35]:
arr_mul[0:2, -1:0:-1, 2] # 支持切片步长为负数

array([[ 0.81279827, -0.50473339,  0.2732999 ,  0.52334807,  0.88503943,
        -1.12964019],
       [-0.32516211, -0.48272546, -1.31839142,  0.83111799,  0.85693079,
        -1.29290909]])

In [36]:
arr_mul[:] # 等价于arr_mul[:, :, :]

array([[[ 3.55034072e-01, -4.34122071e-02, -1.06959704e+00,
          1.05099657e+00],
        [ 1.16312717e+00, -2.20173660e+00, -1.12964019e+00,
         -2.88009890e-01],
        [ 4.17195395e-01,  1.61472707e-01,  8.85039430e-01,
         -5.23143335e-04],
        [ 4.51137733e-01,  2.10636996e+00,  5.23348067e-01,
         -1.01610105e+00],
        [-6.98677186e-01,  9.67172655e-01,  2.73299899e-01,
         -1.05498607e+00],
        [ 2.11753986e+00,  1.27201465e-02, -5.04733390e-01,
          1.86486968e+00],
        [-1.85567022e-01, -9.75778964e-01,  8.12798270e-01,
          3.11920734e-01]],

       [[ 1.17537333e+00, -1.63869449e+00,  1.89006094e+00,
         -1.90127816e-01],
        [-1.13560025e+00,  1.62503986e+00, -1.29290909e+00,
          3.11349295e+00],
        [ 1.09908101e+00,  4.54185328e-01,  8.56930792e-01,
         -2.65200711e-01],
        [ 4.94642894e-01,  4.89948110e-01,  8.31117987e-01,
         -1.66498496e+00],
        [-4.04611676e-01, -6.95302116e-01

In [37]:
arr_mul[::2] # 第一个维度上切片步长为2,范围为整个维度;等价于arr_mul[::2, :, :]

array([[[ 3.55034072e-01, -4.34122071e-02, -1.06959704e+00,
          1.05099657e+00],
        [ 1.16312717e+00, -2.20173660e+00, -1.12964019e+00,
         -2.88009890e-01],
        [ 4.17195395e-01,  1.61472707e-01,  8.85039430e-01,
         -5.23143335e-04],
        [ 4.51137733e-01,  2.10636996e+00,  5.23348067e-01,
         -1.01610105e+00],
        [-6.98677186e-01,  9.67172655e-01,  2.73299899e-01,
         -1.05498607e+00],
        [ 2.11753986e+00,  1.27201465e-02, -5.04733390e-01,
          1.86486968e+00],
        [-1.85567022e-01, -9.75778964e-01,  8.12798270e-01,
          3.11920734e-01]],

       [[ 6.58214739e-02, -6.78889772e-01, -2.22401193e-01,
         -4.03828217e-01],
        [ 2.48416730e+00, -1.87467551e-01,  8.06770212e-01,
          1.89085803e+00],
        [-5.96562232e-01, -1.30129360e+00,  8.41824630e-01,
          1.85644109e-01],
        [-4.14199910e-03, -2.71048612e+00, -2.02746076e+00,
         -1.07281663e+00],
        [ 1.34881501e+00, -1.45586520e+00

In [38]:
arr_complex = np.random.randn(12, 7, 8, 10, 9, 15, 14)
arr_complex.shape

(12, 7, 8, 10, 9, 15, 14)

In [39]:
print(arr_complex[1:5].shape)
print(arr_complex[1:5, :, :, :, :, :].shape)
print(arr_complex[1:5, ...].shape) # ...:剩余维度上所有数据

(4, 7, 8, 10, 9, 15, 14)
(4, 7, 8, 10, 9, 15, 14)
(4, 7, 8, 10, 9, 15, 14)


In [40]:
print(arr_complex[:, :, :, :, :, :, 2:4].shape)
print(arr_complex[..., 2:4].shape)

(12, 7, 8, 10, 9, 15, 2)
(12, 7, 8, 10, 9, 15, 2)


In [41]:
print(arr_complex[2:7, :, :, :, :, :, 4].shape)
print(arr_complex[2:7, ..., 4].shape)


(5, 7, 8, 10, 9, 15)
(5, 7, 8, 10, 9, 15)
