In [14]:
import  numpy as np

arr_mul = np.random.randn(5, 7, 4)
arr_mul

array([[[-0.63128901,  0.2317062 , -0.55385283, -1.53054775],
        [ 0.23155047,  0.23953946,  1.68202461,  0.52580096],
        [ 0.40655537,  0.25248819, -0.17578342,  1.11470263],
        [-1.02476661,  1.52025514,  0.8007708 , -0.64241048],
        [-0.25813823, -0.52101854, -0.10550787,  0.06289214],
        [-0.46463584,  0.58481486,  1.18385073,  1.11798205],
        [-1.49364936,  0.01417793,  1.50439712, -1.41512583]],

       [[ 0.51354163,  0.03126402, -0.51287979,  1.28563905],
        [ 1.103191  , -0.65291967, -0.46681539, -1.54690781],
        [-0.27395461,  0.22944171, -0.76961767, -0.60079742],
        [-0.19751074, -1.51594087,  0.65249785,  1.2713392 ],
        [-0.78113315, -1.01960238, -1.20503647, -0.65577792],
        [-2.39631075, -0.75578523, -0.90533193,  0.06852174],
        [-0.54225083,  0.90719023,  0.09111452, -0.49394512]],

       [[ 0.27882478, -0.3262123 ,  0.09211374,  1.74697777],
        [-0.63057257,  0.89144989, -1.2903124 ,  0.20550829],
    

In [15]:
arr_mul[0] # 从第零个维度开始索引/切片(DataFrame从列开始进行索引切片)

array([[-0.63128901,  0.2317062 , -0.55385283, -1.53054775],
       [ 0.23155047,  0.23953946,  1.68202461,  0.52580096],
       [ 0.40655537,  0.25248819, -0.17578342,  1.11470263],
       [-1.02476661,  1.52025514,  0.8007708 , -0.64241048],
       [-0.25813823, -0.52101854, -0.10550787,  0.06289214],
       [-0.46463584,  0.58481486,  1.18385073,  1.11798205],
       [-1.49364936,  0.01417793,  1.50439712, -1.41512583]])

In [16]:
arr_mul[0, 0, -1] # 索引,若为标量则返回具体数值(且支持负数索引)

-1.530547752275925

In [17]:
arr_mul[0:2] # 切片,返回array

array([[[-0.63128901,  0.2317062 , -0.55385283, -1.53054775],
        [ 0.23155047,  0.23953946,  1.68202461,  0.52580096],
        [ 0.40655537,  0.25248819, -0.17578342,  1.11470263],
        [-1.02476661,  1.52025514,  0.8007708 , -0.64241048],
        [-0.25813823, -0.52101854, -0.10550787,  0.06289214],
        [-0.46463584,  0.58481486,  1.18385073,  1.11798205],
        [-1.49364936,  0.01417793,  1.50439712, -1.41512583]],

       [[ 0.51354163,  0.03126402, -0.51287979,  1.28563905],
        [ 1.103191  , -0.65291967, -0.46681539, -1.54690781],
        [-0.27395461,  0.22944171, -0.76961767, -0.60079742],
        [-0.19751074, -1.51594087,  0.65249785,  1.2713392 ],
        [-0.78113315, -1.01960238, -1.20503647, -0.65577792],
        [-2.39631075, -0.75578523, -0.90533193,  0.06852174],
        [-0.54225083,  0.90719023,  0.09111452, -0.49394512]]])

In [18]:
arr_mul[0:2, 0:3, 0] # 在多个维度上索引/切片

array([[-0.63128901,  0.23155047,  0.40655537],
       [ 0.51354163,  1.103191  , -0.27395461]])

In [19]:
arr_mul[0:2, 0:6:2, 2] # 第一个维度上的切片步长为2,切片范围为0-6

array([[-0.55385283, -0.17578342, -0.10550787],
       [-0.51287979, -0.76961767, -1.20503647]])

In [20]:
arr_mul[0:2, -1:0:-1, 2] # 支持切片步长为负数

array([[ 1.50439712,  1.18385073, -0.10550787,  0.8007708 , -0.17578342,
         1.68202461],
       [ 0.09111452, -0.90533193, -1.20503647,  0.65249785, -0.76961767,
        -0.46681539]])

In [21]:
arr_mul[:] # 等价于arr_mul[:, :, :]

array([[[-0.63128901,  0.2317062 , -0.55385283, -1.53054775],
        [ 0.23155047,  0.23953946,  1.68202461,  0.52580096],
        [ 0.40655537,  0.25248819, -0.17578342,  1.11470263],
        [-1.02476661,  1.52025514,  0.8007708 , -0.64241048],
        [-0.25813823, -0.52101854, -0.10550787,  0.06289214],
        [-0.46463584,  0.58481486,  1.18385073,  1.11798205],
        [-1.49364936,  0.01417793,  1.50439712, -1.41512583]],

       [[ 0.51354163,  0.03126402, -0.51287979,  1.28563905],
        [ 1.103191  , -0.65291967, -0.46681539, -1.54690781],
        [-0.27395461,  0.22944171, -0.76961767, -0.60079742],
        [-0.19751074, -1.51594087,  0.65249785,  1.2713392 ],
        [-0.78113315, -1.01960238, -1.20503647, -0.65577792],
        [-2.39631075, -0.75578523, -0.90533193,  0.06852174],
        [-0.54225083,  0.90719023,  0.09111452, -0.49394512]],

       [[ 0.27882478, -0.3262123 ,  0.09211374,  1.74697777],
        [-0.63057257,  0.89144989, -1.2903124 ,  0.20550829],
    

In [22]:
arr_mul[::2] # 第一个维度上切片步长为2,范围为整个维度;等价于arr_mul[::2, :, :]

array([[[-0.63128901,  0.2317062 , -0.55385283, -1.53054775],
        [ 0.23155047,  0.23953946,  1.68202461,  0.52580096],
        [ 0.40655537,  0.25248819, -0.17578342,  1.11470263],
        [-1.02476661,  1.52025514,  0.8007708 , -0.64241048],
        [-0.25813823, -0.52101854, -0.10550787,  0.06289214],
        [-0.46463584,  0.58481486,  1.18385073,  1.11798205],
        [-1.49364936,  0.01417793,  1.50439712, -1.41512583]],

       [[ 0.27882478, -0.3262123 ,  0.09211374,  1.74697777],
        [-0.63057257,  0.89144989, -1.2903124 ,  0.20550829],
        [-0.19572974,  0.97742923,  0.69049613, -0.37862657],
        [-1.51515111, -0.59409916, -0.42409608, -2.01090663],
        [ 0.66510839, -0.31870064,  0.52552226,  1.99416522],
        [ 0.16162407,  0.98774905,  0.07085204,  0.01728143],
        [-0.50330607,  0.74458816,  0.76079563,  1.44971705]],

       [[-0.43143062, -0.42553501,  0.3522132 , -0.42193142],
        [-1.52362212,  0.27762981, -0.04930389, -0.85460365],
    

In [23]:
arr_complex = np.random.randn(12, 7, 8, 10, 9, 15, 14)
arr_complex.shape

(12, 7, 8, 10, 9, 15, 14)

In [24]:
print(arr_complex[1:5].shape)
print(arr_complex[1:5, :, :, :, :, :].shape)
print(arr_complex[1:5, ...].shape) # ...:剩余维度上所有数据

(4, 7, 8, 10, 9, 15, 14)
(4, 7, 8, 10, 9, 15, 14)
(4, 7, 8, 10, 9, 15, 14)


In [25]:
print(arr_complex[:, :, :, :, :, :, 2:4].shape)
print(arr_complex[..., 2:4].shape)

(12, 7, 8, 10, 9, 15, 2)
(12, 7, 8, 10, 9, 15, 2)


In [26]:
print(arr_complex[2:7, :, :, :, :, :, 4].shape)
print(arr_complex[2:7, ..., 4].shape)


(5, 7, 8, 10, 9, 15)
(5, 7, 8, 10, 9, 15)
