In [1]:
import  numpy as np

In [2]:
arr_scalar = np.array(3)
print(arr_scalar)

3


In [3]:
arr_vector = np.array(range(10), dtype=np.int32)
'''
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.

dtype : data-type, optional
    The desired data-type for the array. If not given, then the type will be determined as the minimum type required to hold the objects in the sequence. 

ndmin : int, optional
    Specifies the minimum number of dimensions that the resulting
    array should have.  Ones will be pre-pended to the shape as
    needed to meet this requirement.   
'''
print(arr_vector)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
arr_lst = np.array([1, 2, 3]) 
print(arr_lst.ndim)
print(arr_lst)
print(arr_lst.T) # nidim=1的数组,转置不变

1
[1 2 3]
[1 2 3]


In [5]:
arr_matrix = np.array([[1, 2, 3], [2, 3, 4]])
print(arr_matrix.shape) # 2 * 3的矩阵
print(arr_matrix)

(2, 3)
[[1 2 3]
 [2 3 4]]


In [6]:
a = [1, 2, 3, 4]
b = ['a', 'b', 'c', 'd', 'e']
arr3 = np.array([a, b])
print(arr3)
print(arr3.ndim) 
print(arr3[0]) # [a, b]不是方阵!a/b被视为一个整体

[list([1, 2, 3, 4]) list(['a', 'b', 'c', 'd', 'e'])]
1
[1, 2, 3, 4]


In [7]:
a1 = [0, 1, 2, 3, 4]
b1 = ['a', 'b', 'c', 'd', 'e']
arr4 = np.array([a1, b1])
print(arr4)
print(arr4.dtype) # 被综合成Unicode类型

[['0' '1' '2' '3' '4']
 ['a' 'b' 'c' 'd' 'e']]
<U11


In [8]:
class A:
    pass

class B:
    pass

a = A()
b = B()

arr_op = np.array([a, b])
print(arr_op.dtype) # Object(对象)类型
print(arr_op) 

object


In [9]:
lst = ['1', '2', '3', '3', 5]
arr_re = np.array(lst, dtype=np.float, ndmin=2).T # 可在数组创建的时候将数字型字符串转换为float
print(arr_re.dtype)
print(arr_re)

float64
[[1.]
 [2.]
 [3.]
 [3.]
 [5.]]


In [10]:
dic = {'a':1, 'b':2, 'c':3, 'd':4}

In [11]:
np.array(dic) # 注意:dic被视为一个整体

array({'a': 1, 'b': 2, 'c': 3, 'd': 4}, dtype=object)

In [12]:
np.array(dic.values()) # 注意:dic.values被视为一个整体

array(dict_values([1, 2, 3, 4]), dtype=object)

In [13]:
np.array(dic.keys()) # 注意:dic.keys()被视为一个整体

array(dict_keys(['a', 'b', 'c', 'd']), dtype=object)

In [14]:
np.array(list(dic.keys())) # 可能是你想要的结果

array(['a', 'b', 'c', 'd'], dtype='<U1')