In [146]:
import numpy as np

In [147]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
part = arr[2:5]
print(id(part))
part = np.array([0, 0, 0, 0, 0]) # part整体重新进行赋值
print(id(part)) # part内存地址改变
arr # arr不变

2170440694080
2170458389040


array([1, 2, 3, 4, 5, 6, 7, 8])

In [148]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
part = arr[2:7]
print(id(part))
part[:] = 9999 # part部分[索引/切]片重新赋值
print(id(part)) # part内存地址不变
arr # arr发生改变(★★★★★修改数组的方法1)

2170457586224
2170457586224


array([   1,    2, 9999, 9999, 9999, 9999, 9999,    8])

In [149]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr[2:5] = np.array([0, 0, 0]) # 直接对该[索引/切片]进行赋值;赋值时必须保证形式相同或可进行广播
arr # arr发生改变(★★★★★修改数组的方法2)

array([1, 2, 0, 0, 0, 6, 7, 8])

In [150]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr[2:][0:4] = np.array([99, 999, 999, 999]) # 直接对该[索引/切片]的[索引/切片]进行赋值;赋值时必须保证形式相同或可进行广播
arr # arr发生改变(★★★★★修改数组的方法3)

array([  1,   2,  99, 999, 999, 999,   7,   8])

## 实例

In [151]:
arr1 = np.arange(60).reshape((3, 4, 5))
arr1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [152]:
part = arr1[:, 2:, 0:3]
part[0, 0, 0] = 1111111111 
arr1

array([[[         0,          1,          2,          3,          4],
        [         5,          6,          7,          8,          9],
        [1111111111,         11,         12,         13,         14],
        [        15,         16,         17,         18,         19]],

       [[        20,         21,         22,         23,         24],
        [        25,         26,         27,         28,         29],
        [        30,         31,         32,         33,         34],
        [        35,         36,         37,         38,         39]],

       [[        40,         41,         42,         43,         44],
        [        45,         46,         47,         48,         49],
        [        50,         51,         52,         53,         54],
        [        55,         56,         57,         58,         59]]])

In [153]:
# 借助广播机制进行修改
arr1[:, 2:, 0:3] = np.array([9, 99, 999]) # [3, 2, 3] boradcasting [3, ] -->[3, 2, 3]
arr1

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [  9,  99, 999,  13,  14],
        [  9,  99, 999,  18,  19]],

       [[ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [  9,  99, 999,  33,  34],
        [  9,  99, 999,  38,  39]],

       [[ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [  9,  99, 999,  53,  54],
        [  9,  99, 999,  58,  59]]])

In [154]:
arr1[:, 2:, 0:3] = np.array([[8, 88, 888]]) # [3, 2, 3] boradcasting [1, 3] -->[3, 2, 3]
arr1

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [  8,  88, 888,  13,  14],
        [  8,  88, 888,  18,  19]],

       [[ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [  8,  88, 888,  33,  34],
        [  8,  88, 888,  38,  39]],

       [[ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [  8,  88, 888,  53,  54],
        [  8,  88, 888,  58,  59]]])

In [155]:
arr1[:, 2:, 0:3] = np.array([[6, 66, 666],
                             [7, 77, 777]]) # [3, 2, 3] boradcasting [2, 3] -->[3, 2, 3]
arr1

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [  6,  66, 666,  13,  14],
        [  7,  77, 777,  18,  19]],

       [[ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [  6,  66, 666,  33,  34],
        [  7,  77, 777,  38,  39]],

       [[ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [  6,  66, 666,  53,  54],
        [  7,  77, 777,  58,  59]]])