In [76]:
import numpy as np

In [77]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(id(arr))

arr[2:5] = np.array([0, 0, 0]) # 直接对切片进行赋值

print(id(arr)) # arr地址不变
print(arr) # arr指向内存的值相应的改变

2409765547344
2409765547344
[1 2 0 0 0 6 7 8]


In [78]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(id(arr))

arr[2] = 100 # 直接对索引值进行赋值

print(id(arr)) # arr地址不变
print(arr) # arr指向内存的值相应的改变

2409765585664
2409765585664
[  1   2 100   4   5   6   7   8]


In [79]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(id(arr))

a = arr[4] # a为不可变数据类型
print(np.shares_memory(a, arr)) # a与arr不共享内存(注:此处共享的是值的内存地址,而不是变量的内存地址)

a = 55

print(id(arr)) # arr地址不变
print(arr) # 修改a对arr指向内存的值无影响

2409765475952
False
2409765475952
[1 2 3 4 5 6 7 8]


In [80]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

a = arr[4:5] # 注意:a为可变数据类型
print(id(a))

# ★★★★★★★★★★★★★★★切片共享内存
print(np.shares_memory(a, arr)) # a与arr共享内存(即a是arr的一个视图)

a += 43 # 可变的类型的追加操作
print(id(a)) # a内存地址不变
print(a) # a指向的值改变

print(arr) # 由于共享内存,故arr指向内存的值相应的改变

2409765475952
True
2409765475952
[48]
[ 1  2  3  4 48  6  7  8]


In [81]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

a = arr[4:5] # 注意:a为可变数据类型
print(id(a))
print(np.shares_memory(a, arr)) # a与arr共享内存

a = a + 43 # 可变的类型的连接操作
print(id(a)) # a内存地址改变,指向新的对象
print(a) # 新的对象的值

print(arr) # 共享的内存没有改变,故arr指向内存的值不变

2409765660672
True
2409765661232
[48]
[1 2 3 4 5 6 7 8]


In [82]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

a = arr[2:5]
print(id(a))
print(np.shares_memory(a, arr)) # a与arr共享内存

a = np.array([0, 0, 0]) # 整体重新进行赋值
print(id(a)) # a内存地址改变,指向新的对象
print(a) # 新的对象的值

print(arr) # 共享的内存没有改变,故arr指向内存的值不变

2409765661872
True
2409765661232
[0 0 0]
[1 2 3 4 5 6 7 8]


In [83]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

a = arr[2:6]
print(id(a))
print(np.shares_memory(a, arr)) # a与arr共享内存

a[:2] = np.array([0, 0]) # 对a的切片进行赋值(可进行广播)
print(id(a)) # a内存地址不变
print(a) # a指向的值改变

print(arr) # 由于共享内存,故arr指向内存的值相应的改变

2409765558912
True
2409765558912
[0 0 5 6]
[1 2 0 0 5 6 7 8]


In [84]:
a = np.arange(30)
b = a.reshape(5, 6)

print(a)
print(b, end='\n\n')

print(id(a))
print(id(b), end='\n\n') # 变量a,b内存地址不同

# ★★★★★★★★★★★★★★★shape操作共享内存
print(np.shares_memory(a, b), end='\n\n') # b与a共享内存

a[0] = 1000000 # 修改a
print(id(a)) # a的内存地址不变
print(a)
print(b, end='\n\n') # 由于共享内存,故b指向内存的值相应的改变

b[-1][-1] = 99999999 # 修改b
print(id(a)) # a的内存地址不变
print(a)
print(b, end='\n\n') # 由于共享内存,故a指向内存的值相应的改变

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

2409765486960
2409765558912

True

2409765486960
[1000000       1       2       3       4       5       6       7       8
       9      10      11      12      13      14      15      16      17
      18      19      20      21      22      23      24      25      26
      27      28      29]
[[1000000       1       2       3       4       5]
 [      6       7       8       9      10      11]
 [     12      13      14      15      16      17]
 [     18      19      20      21      22      23]
 [     24      25      26      27      28      29]]

2409765486960
[ 1000000        1        2        3        4        5        6        7
        8        9       10       11       12       13       14       15
       16       17       18       19       20       21       22       23
       24       

In [85]:
c = np.transpose(b)

# ★★★★★★★★★★★★★★★transpose操作共享内存
np.shares_memory(b, c)

True

In [86]:
d = np.swapaxes(b, 0, 1) # b.T同理

# ★★★★★★★★★★★★★★★swapaxes操作共享内存
np.shares_memory(b, d)

True

In [87]:
e = np.expand_dims(b, 0)

# ★★★★★★★★★★★★★★★expand_dim操作共享内存
np.shares_memory(b, e)

True

In [88]:
f = np.squeeze(e)

# ★★★★★★★★★★★★★★★squeeze操作共享内存
np.shares_memory(e, f)

True

In [89]:
g = b.ravel()
# ★★★★★★★★★★★★★★★ravel操作共享内存★★★★
np.shares_memory(b, g)

True

In [90]:
h = b.flatten()
# ★★★★★★★★★★★★★★★flatten操作不共享内存★★★★
np.shares_memory(b, h)


False