In [21]:
import  torch

In [22]:
a = torch.arange(64)
print(a)
print(id(a))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63])
2339433281000


In [23]:
a.shape # ndim=1

torch.Size([64])

In [24]:
# 完全类似numpy.reshpae
b = torch.reshape(a, (8, 8))
# b = a.reshape(8, 8) # 与上等价
print(b)
print(id(b)) # ★★★★★b与a不指向同一内存

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]])
2339434244840


In [25]:
torch.reshape(a, (-1, 1)) # 等价于b.reshape(64, 1);ndim=2

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30],
        [31],
        [32],
        [33],
        [34],
        [35],
        [36],
        [37],
        [38],
        [39],
        [40],
        [41],
        [42],
        [43],
        [44],
        [45],
        [46],
        [47],
        [48],
        [49],
        [50],
        [51],
        [52],
        [53],
        [54],
        [55],
        [56],
        [57],
        [58],
        [59],
        [60],
        [61],
        [62],
        [63]])

In [26]:
b.reshape(-1, ) # 等价于b.reshape(64, );ndim=1

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [27]:
b.flatten().reshape(8, 8) - b # 不变

tensor([[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]])

In [28]:
tor = torch.randn(2, 7, 7)
tor

tensor([[[ 4.5922e-01,  4.2899e-01, -3.6472e-01, -1.3895e-01,  3.0853e-01,
          -3.4738e-01,  1.2638e+00],
         [ 1.2103e+00,  2.8415e-01, -1.8046e-01,  2.8609e-01, -5.0689e-01,
           1.4746e-01,  1.1846e+00],
         [-1.6543e+00,  6.8558e-01, -8.3799e-01,  1.5020e-01, -3.8345e-02,
           3.4807e-01,  3.6167e-01],
         [-2.0712e+00, -5.4075e-01,  8.3323e-01,  1.5367e-03,  5.4707e-01,
          -1.0601e+00,  1.3723e+00],
         [ 1.8543e+00, -1.3707e+00,  1.3807e+00, -4.9419e-01,  8.1808e-01,
           7.5326e-01,  1.0089e+00],
         [-1.7771e+00,  6.1059e-01, -1.6210e+00, -1.2205e+00, -2.0320e+00,
          -8.7315e-01, -1.5223e+00],
         [-6.7364e-01,  1.2760e+00,  2.8012e+00,  1.1890e+00,  2.2973e-01,
          -1.8871e-01, -1.4397e+00]],

        [[ 1.0117e+00,  5.2873e-01, -1.0922e+00, -1.5769e-01, -1.3649e+00,
           1.1272e+00, -1.0403e+00],
         [-1.0553e+00,  1.2621e+00, -1.5543e+00, -1.4987e-02,  5.2599e-01,
          -1.8058e+00, -4.5

In [29]:
tor1 = tor.reshape(2, 7*7) # 向量化数据
tor1

tensor([[ 4.5922e-01,  4.2899e-01, -3.6472e-01, -1.3895e-01,  3.0853e-01,
         -3.4738e-01,  1.2638e+00,  1.2103e+00,  2.8415e-01, -1.8046e-01,
          2.8609e-01, -5.0689e-01,  1.4746e-01,  1.1846e+00, -1.6543e+00,
          6.8558e-01, -8.3799e-01,  1.5020e-01, -3.8345e-02,  3.4807e-01,
          3.6167e-01, -2.0712e+00, -5.4075e-01,  8.3323e-01,  1.5367e-03,
          5.4707e-01, -1.0601e+00,  1.3723e+00,  1.8543e+00, -1.3707e+00,
          1.3807e+00, -4.9419e-01,  8.1808e-01,  7.5326e-01,  1.0089e+00,
         -1.7771e+00,  6.1059e-01, -1.6210e+00, -1.2205e+00, -2.0320e+00,
         -8.7315e-01, -1.5223e+00, -6.7364e-01,  1.2760e+00,  2.8012e+00,
          1.1890e+00,  2.2973e-01, -1.8871e-01, -1.4397e+00],
        [ 1.0117e+00,  5.2873e-01, -1.0922e+00, -1.5769e-01, -1.3649e+00,
          1.1272e+00, -1.0403e+00, -1.0553e+00,  1.2621e+00, -1.5543e+00,
         -1.4987e-02,  5.2599e-01, -1.8058e+00, -4.5707e-01, -8.8408e-01,
          3.7981e-01, -2.6694e-02, -2.2292e-01,  3

In [30]:
tor2 = tor1.reshape(2, 7, 7) # 按原顺序恢复成原shape
tor2 - tor

tensor([[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]])