In [56]:
import torch
import numpy as np

a = np.array([[1.2, 2, 3],
              [2, 3, 4]])
x = torch.tensor(a) 
x

tensor([[1.2000, 2.0000, 3.0000],
        [2.0000, 3.0000, 4.0000]], dtype=torch.float64)

In [57]:
# 类似numpy相关属性
x.dtype

torch.float64

In [58]:
x.ndim # 或使用x.dim()

2

In [59]:
x.shape # 或使用x.size()

torch.Size([2, 3])

In [60]:
list(x.shape)

[2, 3]

In [61]:
x.shape[0]

2

In [62]:
x.shape[1]

3

In [63]:
# 类似于arr.size
x.() # tensor元素个数

6

In [64]:
y = torch.randn(3, 5, 7)
y.shape

torch.Size([3, 5, 7])

In [65]:
y.T.shape # 等价于torch.transpose(x, 0, -1),若self.ndim <2则返回其本身

torch.Size([7, 5, 3])

In [66]:
torch.transpose(y, 0, -1).shape

torch.Size([7, 5, 3])

In [67]:
y.device

device(type='cpu')

In [68]:
y.data

tensor([[[-1.0821, -2.0806,  0.2941,  0.4895,  0.8743,  0.6631,  0.1978],
         [ 1.7081,  0.8692, -1.3229,  0.6947, -1.1287,  0.4034,  0.2898],
         [-1.1870, -0.5983, -0.7190, -1.6367, -0.6257,  0.6560,  2.0567],
         [ 0.0745, -1.2393, -1.2373, -1.2752,  0.2288, -0.6782, -0.5309],
         [-0.6455,  0.4318, -1.6938,  0.8140, -0.3378,  0.7726,  0.4972]],

        [[ 0.8526,  0.1939,  0.3894,  0.5352,  0.2449, -1.7691, -1.3750],
         [-2.0660, -0.8042,  0.5385,  0.7059,  0.8022, -1.1418, -0.5717],
         [-0.1991, -1.6599, -0.3703, -1.3076, -0.9768, -0.5226, -0.2816],
         [-0.7792, -0.0091,  1.0136, -1.1173,  0.4929, -2.2535, -0.4162],
         [-0.4011, -1.4360,  0.5733, -0.3593, -2.1880, -0.5878, -1.0791]],

        [[ 0.7774,  2.8526, -0.0783, -0.5773,  0.7583, -2.5065, -0.4522],
         [-1.7968, -0.4883,  0.3049, -0.8745, -0.5705,  0.1353, -0.9732],
         [ 0.7726,  0.2800, -0.6331, -0.8548,  0.3464, -0.3153,  1.7089],
         [-0.2351,  0.5503,  1.571

In [69]:
print(id(y))
y.data = torch.ones_like(y) # 修改的仅是y的值(y内存地址不变)
print(y)
print(id(y))

2172627686568
tensor([[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]])
2172627686568
