In [1]:
import torch
# 完全类似numpy索引切片

In [2]:
tor_mul = torch.randn(5, 7, 4)
tor_mul

tensor([[[ 1.8655, -0.9040, -1.2698,  1.2421],
         [ 0.7226, -0.2224,  2.0278, -0.4496],
         [ 0.3815, -0.7924, -0.0947,  0.1112],
         [-0.5709, -2.2149, -0.0036,  0.2795],
         [ 0.3288,  0.3226,  0.7697,  0.8745],
         [-1.7707,  0.4983,  0.1238,  2.4063],
         [-0.6059, -0.3428,  0.0038,  0.6425]],

        [[-0.1695,  1.2361, -1.2399,  0.1276],
         [-0.8089,  0.2329,  0.6141,  0.3113],
         [-0.0036, -1.4527,  0.3615,  0.6474],
         [-0.3593, -2.4587,  1.2476, -0.3347],
         [-0.3261,  0.7570,  1.3578,  0.5643],
         [-0.7538, -0.4363,  1.3775, -1.6267],
         [ 1.1084, -2.5666,  0.7891,  0.3076]],

        [[ 0.5466, -1.6739,  0.0768, -1.7763],
         [-0.5695,  1.3058, -0.5342, -0.5354],
         [ 1.1909, -0.6078,  0.7771, -0.0884],
         [-0.3262, -0.9057,  0.6720,  0.3253],
         [ 0.4718, -0.1700, -1.2464,  0.8564],
         [ 0.4239,  0.6705,  1.0008, -0.8861],
         [ 1.3850, -0.5093,  1.6154, -0.6480]],

       

In [3]:
tor_mul[0] # 从第零个维度开始索引切片(DataFrame从列开始进行索引切片)

tensor([[ 1.8655, -0.9040, -1.2698,  1.2421],
        [ 0.7226, -0.2224,  2.0278, -0.4496],
        [ 0.3815, -0.7924, -0.0947,  0.1112],
        [-0.5709, -2.2149, -0.0036,  0.2795],
        [ 0.3288,  0.3226,  0.7697,  0.8745],
        [-1.7707,  0.4983,  0.1238,  2.4063],
        [-0.6059, -0.3428,  0.0038,  0.6425]])

In [4]:
tor_mul[0, 0, -1] # 索引,返回tensor.支持负数索引

tensor(1.2421)

In [5]:
tor_mul[0:2] # 切片,返回tensor

tensor([[[ 1.8655, -0.9040, -1.2698,  1.2421],
         [ 0.7226, -0.2224,  2.0278, -0.4496],
         [ 0.3815, -0.7924, -0.0947,  0.1112],
         [-0.5709, -2.2149, -0.0036,  0.2795],
         [ 0.3288,  0.3226,  0.7697,  0.8745],
         [-1.7707,  0.4983,  0.1238,  2.4063],
         [-0.6059, -0.3428,  0.0038,  0.6425]],

        [[-0.1695,  1.2361, -1.2399,  0.1276],
         [-0.8089,  0.2329,  0.6141,  0.3113],
         [-0.0036, -1.4527,  0.3615,  0.6474],
         [-0.3593, -2.4587,  1.2476, -0.3347],
         [-0.3261,  0.7570,  1.3578,  0.5643],
         [-0.7538, -0.4363,  1.3775, -1.6267],
         [ 1.1084, -2.5666,  0.7891,  0.3076]]])

In [6]:
tor_mul[0:2, 0:3, 0] # 在多个维度上索引切片

tensor([[ 1.8655,  0.7226,  0.3815],
        [-0.1695, -0.8089, -0.0036]])

In [7]:
tor_mul[0:2, 0:6:2, 2] # 第一个维度上的切片步长为2(不支持步长为负数),切片范围为0-6

tensor([[-1.2698, -0.0947,  0.7697],
        [-1.2399,  0.3615,  1.3578]])

In [8]:
tor_mul[:] # 等价于tor_mul[:, :, :]

tensor([[[ 1.8655, -0.9040, -1.2698,  1.2421],
         [ 0.7226, -0.2224,  2.0278, -0.4496],
         [ 0.3815, -0.7924, -0.0947,  0.1112],
         [-0.5709, -2.2149, -0.0036,  0.2795],
         [ 0.3288,  0.3226,  0.7697,  0.8745],
         [-1.7707,  0.4983,  0.1238,  2.4063],
         [-0.6059, -0.3428,  0.0038,  0.6425]],

        [[-0.1695,  1.2361, -1.2399,  0.1276],
         [-0.8089,  0.2329,  0.6141,  0.3113],
         [-0.0036, -1.4527,  0.3615,  0.6474],
         [-0.3593, -2.4587,  1.2476, -0.3347],
         [-0.3261,  0.7570,  1.3578,  0.5643],
         [-0.7538, -0.4363,  1.3775, -1.6267],
         [ 1.1084, -2.5666,  0.7891,  0.3076]],

        [[ 0.5466, -1.6739,  0.0768, -1.7763],
         [-0.5695,  1.3058, -0.5342, -0.5354],
         [ 1.1909, -0.6078,  0.7771, -0.0884],
         [-0.3262, -0.9057,  0.6720,  0.3253],
         [ 0.4718, -0.1700, -1.2464,  0.8564],
         [ 0.4239,  0.6705,  1.0008, -0.8861],
         [ 1.3850, -0.5093,  1.6154, -0.6480]],

       

In [9]:
tor_mul[::2] # 第一个维度上切片步长为2,范围为整个维度;等价于tor_mul[::2, :, :]

tensor([[[ 1.8655, -0.9040, -1.2698,  1.2421],
         [ 0.7226, -0.2224,  2.0278, -0.4496],
         [ 0.3815, -0.7924, -0.0947,  0.1112],
         [-0.5709, -2.2149, -0.0036,  0.2795],
         [ 0.3288,  0.3226,  0.7697,  0.8745],
         [-1.7707,  0.4983,  0.1238,  2.4063],
         [-0.6059, -0.3428,  0.0038,  0.6425]],

        [[ 0.5466, -1.6739,  0.0768, -1.7763],
         [-0.5695,  1.3058, -0.5342, -0.5354],
         [ 1.1909, -0.6078,  0.7771, -0.0884],
         [-0.3262, -0.9057,  0.6720,  0.3253],
         [ 0.4718, -0.1700, -1.2464,  0.8564],
         [ 0.4239,  0.6705,  1.0008, -0.8861],
         [ 1.3850, -0.5093,  1.6154, -0.6480]],

        [[ 0.3871,  1.6407,  0.8136,  0.7035],
         [ 0.8344,  0.3510,  0.2438,  1.9180],
         [-0.3298, -1.2324, -0.7222,  0.3744],
         [-1.5006, -0.5007,  0.2585,  0.9337],
         [-0.2858,  1.6660,  0.1677,  0.1971],
         [-0.3620,  0.2300, -1.7301,  0.8544],
         [ 0.2819, -0.1675,  0.2824, -0.7970]]])

In [10]:
tor_complex = torch.randn(12, 7, 8, 10, 9, 15, 14)
tor_complex.shape

torch.Size([12, 7, 8, 10, 9, 15, 14])

In [11]:
print(tor_complex[1:5].shape)
print(tor_complex[1:5, :, :, :, :, :].shape)
print(tor_complex[1:5, ...].shape) # ...:剩余维度上所有数据

torch.Size([4, 7, 8, 10, 9, 15, 14])
torch.Size([4, 7, 8, 10, 9, 15, 14])
torch.Size([4, 7, 8, 10, 9, 15, 14])


In [12]:
print(tor_complex[:, :, :, :, :, :, 2:4].shape)
print(tor_complex[..., 2:4].shape)

torch.Size([12, 7, 8, 10, 9, 15, 2])
torch.Size([12, 7, 8, 10, 9, 15, 2])


In [13]:
print(tor_complex[2:7, :, :, :, :, :, 4].shape)
print(tor_complex[2:7, ..., 4].shape)


torch.Size([5, 7, 8, 10, 9, 15])
torch.Size([5, 7, 8, 10, 9, 15])
