## 交集

In [1]:
import  numpy as np
np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])
'''
Find the intersection of two arrays.

Return the sorted, unique values that are in both of the input arrays.
'''

array([1, 3])

In [2]:
# To intersect more than two arrays, use functools.reduce:
from functools import reduce
reduce(np.intersect1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))

array([3])

## 并集

In [3]:
np.union1d([-1, 0, 1], [-2, 0, 2])

array([-2, -1,  0,  1,  2])

In [4]:
# To find the union of more than two arrays, use functools.reduce:
reduce(np.union1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))

array([1, 2, 3, 4, 6])

## 差集

In [ ]:
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 4, 5, 6])
np.setdiff1d(a, b)

