In [1]:
import torch

In [2]:
scale = torch.tensor([1.])
scale.item() # Returns the value of this tensor as a standard Python number. This only works for tensors with one element

1.0

In [3]:

tor = torch.tensor([[1, 2, 3, 4, 5],
                    [2, 3, 4, 5, 6]])
tor

tensor([[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]])

In [4]:
lst = tor.tolist() # Returns the tensor as a (nested) list
lst

[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]]

In [5]:
lst[0][0] = 9999
lst

[[9999, 2, 3, 4, 5], [2, 3, 4, 5, 6]]

In [6]:
tor # tor不变;tor,lst共享内存

tensor([[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]])

In [7]:
arr = tor.numpy() # Returns self tensor as a NumPy ndarray
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]], dtype=int64)

In [8]:
arr[0][0] = 1111111111
arr

array([[1111111111,          2,          3,          4,          5],
       [         2,          3,          4,          5,          6]],
      dtype=int64)

In [9]:
tor # tor发生改变;tor,arr共享内存


tensor([[1111111111,          2,          3,          4,          5],
        [         2,          3,          4,          5,          6]])