In [35]:
import torch
import numpy as np

In [36]:
# 参考ndarray的储存结构.ipynb
tor = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])
print(id(tor))

a = tor[4] # 注意:a为标量tensor,故a为可变数据类型
print(np.shares_memory(a, tor)) # a与arr不共享内存(注:此处共享的是值的内存地址,而不是变量的内存地址)

a += 100 # 可变的类型的追加操作

print(id(tor)) # arr地址不变
print(tor) # 由于共享内存,故arr指向内存的值相应的改变

2202216288808
True
2202216288808
tensor([  1,   2,   3,   4, 105,   6,   7,   8])


In [37]:
a = torch.arange(30)
b = a.reshape(5, 6)

print(a)
print(b, end='\n\n')

print(id(a))
print(id(b), end='\n\n') # a,b内存地址不同

# ★★★★★★★★★★★★★★★shape操作共享内存
print(np.shares_memory(a, b), end='\n\n') # b与a共享内存

a[0] = 1000000 # 修改a
print(id(a))
print(a) # a的内存不变
print(b, end='\n\n') # 由于共享内存,故b指向内存的值相应的改变

b[-1][-1] = 99999999 # 修改b
print(id(a)) # a的内存地址不变
print(a)
print(b, end='\n\n') # 由于共享内存,故a指向内存呢的值相应的改变

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]])

2202216829240
2202219921640

True

2202216829240
tensor([1000000,       1,       2,       3,       4,       5,       6,       7,
              8,       9,      10,      11,      12,      13,      14,      15,
             16,      17,      18,      19,      20,      21,      22,      23,
             24,      25,      26,      27,      28,      29])
tensor([[1000000,       1,       2,       3,       4,       5],
        [      6,       7,       8,       9,      10,      11],
        [     12,      13,      14,      15,      16,      17],
        [     18,      19,      20,      21,      22,      23],
        [     24,      25,      26,      27,      28,      29]])

2202216829240
ten

In [38]:
c = a.detach()

# ★★★★★★★★★★★★★★★detach操作共享内存
np.shares_memory(b, c)

True

In [39]:
d = a.clone()

# ★★★★★★★★★★★★★★★clone操作不共享内存★★★★
np.shares_memory(b, d)

False

In [40]:
e = a.flatten()

# ★★★★★★★★★★★★★★★flatten操作共享内存
np.shares_memory(b, e)

True

In [41]:
f = b.transpose(0, 1)

# ★★★★★★★★★★★★★★★transpose操作共享内存
np.shares_memory(b, f)

True

In [42]:
g = b.permute(1, 0) # b.T同理

# ★★★★★★★★★★★★★★★permute操作共享内存
np.shares_memory(b, g)

True

In [43]:
h = torch.unsqueeze(b, 0)

# ★★★★★★★★★★★★★★★unsqueeze操作共享内存
np.shares_memory(b, h)

True

In [44]:
j = torch.squeeze(h)

# ★★★★★★★★★★★★★★★squeeze操作共享内存
np.shares_memory(h, j)




True