In [1]:
import torch
# 完全类似numpy array的修改(基本索引切片)

In [2]:
tor = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])
part = tor[2:5]
print(id(part))
part = torch.tensor([0, 0, 0, 0, 0]) # part整体重新进行赋值
print(id(part)) # part内存地址改变
tor # tor不变

1302986751336
1302962943304


tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
tor = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])
part = tor[2:7]
print(id(part))
part[:] = 9999 # part部分[索引/切片]重新赋值
print(id(part)) # part内存地址不变
tor # tor发生改变(★★★★★修改tensor的方法1)

1302986783064
1302986783064


tensor([   1,    2, 9999, 9999, 9999, 9999, 9999,    8])

In [4]:
tor = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])
tor[2:5] = torch.tensor([0, 0, 0]) # 直接对该[索引/切片]进行赋值;赋值时必须保证形式相同或可进行广播
tor # tor发生改变(★★★★★修改tensor的方法2)

tensor([1, 2, 0, 0, 0, 6, 7, 8])

In [5]:
tor = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])
tor[2:][0:4] = torch.tensor([99, 999, 999, 999]) # 直接对该[索引/切片]的[索引/切片]进行赋值;赋值时必须保证形式相同或可进行广播
tor # tor发生改变(★★★★★修改tensor的方法3)

tensor([  1,   2,  99, 999, 999, 999,   7,   8])

## 实例

In [6]:
tor1 = torch.arange(60).reshape((3, 4, 5))
tor1

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])

In [7]:
part = tor1[:, 2:, 0:3]
part[0, 0, 0] = 1111111111 
tor1

tensor([[[         0,          1,          2,          3,          4],
         [         5,          6,          7,          8,          9],
         [1111111111,         11,         12,         13,         14],
         [        15,         16,         17,         18,         19]],

        [[        20,         21,         22,         23,         24],
         [        25,         26,         27,         28,         29],
         [        30,         31,         32,         33,         34],
         [        35,         36,         37,         38,         39]],

        [[        40,         41,         42,         43,         44],
         [        45,         46,         47,         48,         49],
         [        50,         51,         52,         53,         54],
         [        55,         56,         57,         58,         59]]])

In [8]:
# 借助广播机制进行修改
tor1[:, 2:, 0:3] = torch.tensor([9, 99, 999]) # [3, 2, 3] boradcasting [3, ] -->[3, 2, 3]
tor1

tensor([[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [  9,  99, 999,  13,  14],
         [  9,  99, 999,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [  9,  99, 999,  33,  34],
         [  9,  99, 999,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [  9,  99, 999,  53,  54],
         [  9,  99, 999,  58,  59]]])

In [9]:
tor1[:, 2:, 0:3] = torch.tensor([[8, 88, 888]]) # [3, 2, 3] boradcasting [1, 3] -->[3, 2, 3]
tor1

tensor([[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [  8,  88, 888,  13,  14],
         [  8,  88, 888,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [  8,  88, 888,  33,  34],
         [  8,  88, 888,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [  8,  88, 888,  53,  54],
         [  8,  88, 888,  58,  59]]])

In [10]:
tor1[:, 2:, 0:3] = torch.tensor([[6, 66, 666],
                             [7, 77, 777]]) # [3, 2, 3] boradcasting [2, 3] -->[3, 2, 3]
tor1

tensor([[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [  6,  66, 666,  13,  14],
         [  7,  77, 777,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [  6,  66, 666,  33,  34],
         [  7,  77, 777,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [  6,  66, 666,  53,  54],
         [  7,  77, 777,  58,  59]]])