In [6]:
import torch

tor = torch.tensor([[1, 2, 3, 4, 5],
                    [2, 3, 4, 5, 6]])
tor

tensor([[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]])

In [7]:
lst = tor.tolist() # Returns the tensor as a (nested) list
lst

[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]]

In [10]:
lst[0][0] = 9999
lst

[[9999, 2, 3, 4, 5], [2, 3, 4, 5, 6]]

In [11]:
tor # tor不变;tor,lst共享内存

tensor([[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]])

In [12]:
arr = tor.numpy() # Returns self tensor as a NumPy ndarray
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]], dtype=int64)

In [13]:
arr[0][0] = 1111111111
arr

array([[1111111111,          2,          3,          4,          5],
       [         2,          3,          4,          5,          6]],
      dtype=int64)

In [14]:
tor # tor发生改变;tor,arr共享内存

tensor([[1111111111,          2,          3,          4,          5],
        [         2,          3,          4,          5,          6]])