In [149]:
import torch
import numpy as np

In [150]:
# 类似numpy.array
x = torch.tensor(3.0) # 标量
x

tensor(3.)

In [151]:
x = torch.tensor([5.5, 3]) # 向量
x

tensor([5.5000, 3.0000])

In [152]:
x = torch.tensor(range(10))
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
a = np.array([[1.2, 2, 3],
              [2, 3, 4]])
x = torch.tensor(a) # 从numpy创建tensor(矩阵)
x

tensor([[1.2000, 2.0000, 3.0000],
        [2.0000, 3.0000, 4.0000]], dtype=torch.float64)

In [154]:
x = torch.tensor([1, 2, 3, 4, 5], 
                 dtype=torch.float32) # 指定数据类型
x.dtype

torch.float32

In [155]:
x = torch.tensor(['1', '2']) # 不支持str数据类型
x

ValueError: too many dimensions 'str'