In [30]:
import torch

### 标准正态分布抽样 randn/randn_like
1. 完全类似numpy.random.randn
### 正态分布抽样:normal
1. 类似numpy.random.normal

In [31]:
torch.randn(2, 3) # 标准正态分布抽样

tensor([[-0.1302,  2.1277,  2.1397],
        [-0.5838, -0.1933, -0.3768]])

In [32]:
torch.randn(50)

tensor([-1.7688, -1.6442,  0.7851,  1.1222, -0.6016,  0.6779,  0.6942, -0.8102,
        -2.0582, -1.0336, -0.4019, -0.0810,  0.2318, -1.2495,  1.0737,  0.9129,
        -0.5035,  0.3417,  0.3059, -0.1591, -0.4592, -0.1497, -0.7017,  0.8286,
         1.0339, -0.6656,  0.7632,  0.3321, -0.4755,  0.8998, -0.1128,  0.7764,
        -1.1002, -1.5269,  1.4014, -0.0800,  0.3870, -1.4535, -2.2475, -0.7427,
        -0.6827,  2.7434, -0.9789, -0.1425, -0.9643,  1.9881,  0.5459,  1.6951,
        -2.7362,  0.0115])

In [33]:
torch.normal(mean=2, std=3, size=(2, 4)) # 从均值为2,标准差为3的正态分布抽样

tensor([[ 0.5170,  5.3673,  1.4553,  1.4594],
        [ 1.3596,  0.7657, -1.4524,  0.6361]])

In [34]:
torch.normal(mean=torch.arange(1., 11.), # 每个元素的均值
             std=torch.arange(1, 0, -0.1)) # 每个元素的标准差

tensor([ 0.6110,  2.5566,  2.6670,  4.7917,  5.5965,  6.6528,  6.7187,  7.4276,
         8.7445, 10.0011])

In [35]:
torch.normal(mean=0.5, std=torch.arange(1., 6.)) # 所有元素均值相同

tensor([ 1.5905,  0.7229,  0.7524, -4.0174,  4.0385])

In [36]:
torch.normal(mean=torch.arange(1., 6.), std=1) # 所有元素标准差相同

tensor([-0.2646,  2.1908,  2.3380,  4.1032,  6.0422])

### [0,1]均匀分布抽样:rand
1. 完全类似numpy.rand

In [37]:
torch.rand(3)

tensor([0.0933, 0.1560, 0.9150])

In [38]:
torch.rand(2, 3)

tensor([[0.5960, 0.6218, 0.9088],
        [0.5680, 0.5190, 0.7014]])

### 随机整数抽样:randint;randperm
1. 类似random.randint

In [39]:
torch.randint(3, 8, size=(3, 4)) # 不包括末尾元素

tensor([[4, 4, 5, 7],
        [6, 5, 7, 7],
        [7, 6, 6, 3]])

In [40]:
idx = torch.randperm(3) # Returns a random permutation of integers from 0 to n - 1.
idx

tensor([0, 1, 2])

In [41]:
x1 = torch.tensor([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
x2 = torch.tensor([[1.0, 1.0, 1.0], [2.0, 2.0, 2.0], [3.0, 3.0, 3.0]])
print(x1[idx])
print(x2[idx]) # 实现了sklearn.utils.shuffle函数的功能

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])
tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])


In [42]:
### 其他分布抽样

In [43]:
from scipy.stats import beta # 贝塔分布
torch.tensor(beta.rvs(a=2, b=2, size=10).reshape(2, 5)) # 先从scipy生成随机样本


tensor([[0.2583, 0.5267, 0.8308, 0.8406, 0.5493],
        [0.5578, 0.5032, 0.3866, 0.4658, 0.6156]], dtype=torch.float64)