In [21]:
import torch

### zeros/zeros_like
1. 完全类似numpy.zeros
2. 完全类似numpy.zeros_like

In [22]:
torch.zeros((2, 3)) # 也可以是torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [23]:
put = torch.empty((2, 3))
torch.zeros_like(put)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### ones/ones_like
1. 完全类似numpy.ones
2. 完全类似numpy.ones_like

In [24]:
torch.ones((2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

### eye
1. 类似numpy.eye

In [25]:
# 对角线元素为1
torch.eye(3) # 默认m=n

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [26]:
torch.eye(n=3, # 行数
          m=6) # 列数

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.]])

### empty/empty_like
1. 完全类似numpy.empty
2. 完全类似numpy.empty_like

In [27]:
torch.empty((2, 3)) # 结果非常不均衡

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### full/full_like
1. 完全类似numpy.full
2. 完全类似numpy_like

In [28]:
torch.full((2, 3), 3.141592)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

### diag
1. 完全类似numpy.diag

In [29]:
# Get the square matrix where the input vector is the diagonal
a = torch.randn(3)

In [30]:
torch.diag(a)

tensor([[-0.7804,  0.0000,  0.0000],
        [ 0.0000, -0.4046,  0.0000],
        [ 0.0000,  0.0000, -0.4403]])

In [31]:
torch.diag(a, 1)

tensor([[ 0.0000, -0.7804,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.4046,  0.0000],
        [ 0.0000,  0.0000,  0.0000, -0.4403],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])

In [32]:
torch.diag(a, -1)

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000],
        [-0.7804,  0.0000,  0.0000,  0.0000],
        [ 0.0000, -0.4046,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.4403,  0.0000]])

In [33]:
# Get the k-th diagonal of a given matrix
b = torch.randn(3, 3)
b

tensor([[ 0.4842,  1.5916,  0.2613],
        [-1.3347, -1.0835,  0.6088],
        [-0.0471,  1.4111,  1.0036]])

In [34]:
torch.diag(b)

tensor([ 0.4842, -1.0835,  1.0036])

In [35]:
torch.diag(b, -1)

tensor([-1.3347,  1.4111])

In [36]:
torch.diag(b, 2)


tensor([0.2613])