In [64]:
import torch

### 标准正态分布抽样 randn/randn_like
1. 完全类似numpy.random.randn
### 正态分布抽样:normal
1. 类似numpy.random.normal

In [65]:
torch.randn(2, 3) # 标准正态分布抽样

tensor([[ 0.8900,  0.3583,  0.3789],
        [-0.5869, -0.1590, -0.8985]])

In [66]:
torch.randn(50)

tensor([ 1.1578, -0.7134,  0.6829, -1.2970,  0.7290, -0.1136, -0.1732,  0.5193,
         0.2010,  0.4383,  0.3521, -1.1380,  1.1511, -1.3558, -0.8770,  0.5336,
         2.4130,  1.0105,  2.0250,  0.1205, -0.9091,  0.0080, -0.2084,  1.0108,
         0.9238, -0.3258, -0.6549, -0.4065, -0.7920,  0.8124, -1.1882,  0.6420,
         0.2789,  1.7786,  1.4456, -0.2850,  0.0542, -0.9156,  1.2007, -0.6980,
        -0.5927,  2.5519, -1.3021, -1.1764, -0.2708,  0.9985, -0.3412, -1.1341,
         0.8463,  1.3633])

In [67]:
torch.normal(mean=2, std=3, size=(2, 4)) # 从均值为2,标准差为3的正态分布抽样

tensor([[-0.2861, -2.7954,  1.1863,  3.8967],
        [-0.4861,  6.0800,  1.4761,  1.2795]])

In [68]:
torch.normal(mean=torch.arange(1., 11.).reshape(2, 5), # 每个元素的均值
             std=torch.arange(1, 0, -0.1).reshape(2, 5)) # 每个元素的标准差

tensor([[2.5042, 1.4883, 3.1115, 3.9319, 5.0564],
        [6.2253, 6.6115, 7.8672, 8.8449, 9.9773]])

In [69]:
torch.normal(mean=0.5, std=torch.arange(1., 25.)) # 所有元素均值相同(不同标准差)

tensor([ -1.4696,  -0.7905,   1.9935,   2.7152,  10.9756,  -0.3563,  -2.4708,
          0.6566,  -1.4803,   2.9646,   2.0078,  11.4402,  16.8313, -18.6547,
        -17.7579, -19.6733,  -2.4860, -15.1800, -16.3625,  10.1626,  -6.7304,
         22.0257, -12.5364, -39.6581])

In [70]:
torch.normal(mean=torch.arange(1., 25.).reshape(4, 6), std=1) # 所有元素标准差相同(不同均值)

tensor([[ 0.6563, -0.2725,  3.7685,  2.1485,  5.9560,  5.6508],
        [ 6.4754,  7.4837,  9.8371, 10.7820, 11.6896, 12.3169],
        [12.8481, 14.6675, 15.0931, 15.1788, 17.7299, 18.0257],
        [18.6300, 20.2294, 21.4968, 20.1696, 23.1347, 24.0763]])

### [0,1]均匀分布抽样:rand
1. 完全类似numpy.rand

In [71]:
torch.rand(3)

tensor([0.5145, 0.9235, 0.8030])

In [72]:
torch.rand(2, 3)

tensor([[0.6696, 0.5091, 0.9063],
        [0.8189, 0.5752, 0.4607]])

### 随机整数抽样:randint;randperm
1. 类似random.randint

In [73]:
torch.randint(3, 8, size=(3, 4)) # 不包括末尾元素

tensor([[5, 6, 7, 6],
        [6, 4, 4, 7],
        [6, 6, 3, 7]])

In [74]:
idx = torch.randperm(3) # Returns a random permutation of integers from 0 to n - 1.
idx

tensor([0, 2, 1])

In [75]:
x1 = torch.tensor([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
x2 = torch.tensor([[1.0, 1.0, 1.0], [2.0, 2.0, 2.0], [3.0, 3.0, 3.0]])
print(x1[idx])
print(x2[idx]) # 实现了sklearn.utils.shuffle函数的功能

tensor([[1, 1, 1],
        [3, 3, 3],
        [2, 2, 2]])
tensor([[1., 1., 1.],
        [3., 3., 3.],
        [2., 2., 2.]])


In [76]:
### 其他分布抽样

In [77]:
from scipy.stats import beta # 贝塔分布
torch.tensor(beta.rvs(a=2, b=2, size=10).reshape(2, 5)) # 先从scipy生成随机样本


tensor([[0.2252, 0.3433, 0.3096, 0.4310, 0.5996],
        [0.8422, 0.3712, 0.4905, 0.3500, 0.3514]], dtype=torch.float64)