In [4]:
import numpy as np

x = np.array([1, 2, 3])


np.broadcast_to(x, (2, 3)) # Broadcast an array to a new shape.

array([[1, 2, 3],
       [1, 2, 3]])

In [5]:
np.broadcast_to(x, (5, 4, 3)) # 和广播机制规则一致

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [6]:
x # x不变



array([1, 2, 3])