In [11]:
import  numpy as np

In [12]:
a = np.arange(64)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [13]:
a.shape # ndim=1

(64,)

In [14]:
b = np.reshape(a, (8, 8))
# b = a.reshape(8, 8) # 与上等价
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [15]:
b.reshape(-1, 1) # 等价于b.reshape(64, 1);ndim=2

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63]])

In [16]:
b.reshape(-1, ) # 等价于b.reshape(64, );ndim=1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [17]:
b.flatten().reshape(8, 8) - b # 不变

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
arr = np.random.randn(2, 7, 7)
arr

array([[[-0.88146242, -1.51847213, -0.00547962, -0.15940581,
          0.28119967,  0.42304509, -0.61819252],
        [-0.34538507,  1.4227042 ,  0.18742029,  0.52689226,
         -0.83806367,  0.42936308,  1.08122658],
        [ 1.93365466,  0.67764996,  0.51570803, -1.32023715,
         -0.59694411, -1.2108139 ,  0.23533278],
        [ 0.3715466 , -1.40829851, -2.44953778,  0.33382509,
          2.06207832,  0.40446964,  1.09315641],
        [ 1.95059913, -0.57295635, -1.95211855,  0.18648775,
          0.0893678 ,  0.46802978,  0.73142397],
        [ 1.11577482,  0.54211865,  1.05752617,  0.14208744,
          0.63841199, -0.19766867,  0.72088892],
        [-0.27304322, -0.89170678, -2.18684123,  1.55695327,
          0.09894319, -0.45222442, -0.91090876]],

       [[-1.10131326,  0.72679666,  0.60866562, -1.00396207,
         -0.7150907 , -0.01723373, -0.18755455],
        [-1.20682856,  0.59301323,  0.53335276, -0.40010804,
         -1.87649249, -0.97680874, -0.59682431],
        

In [19]:
arr1 = arr.reshape(2, 7*7) # 向量化数据
arr1

array([[-0.88146242, -1.51847213, -0.00547962, -0.15940581,  0.28119967,
         0.42304509, -0.61819252, -0.34538507,  1.4227042 ,  0.18742029,
         0.52689226, -0.83806367,  0.42936308,  1.08122658,  1.93365466,
         0.67764996,  0.51570803, -1.32023715, -0.59694411, -1.2108139 ,
         0.23533278,  0.3715466 , -1.40829851, -2.44953778,  0.33382509,
         2.06207832,  0.40446964,  1.09315641,  1.95059913, -0.57295635,
        -1.95211855,  0.18648775,  0.0893678 ,  0.46802978,  0.73142397,
         1.11577482,  0.54211865,  1.05752617,  0.14208744,  0.63841199,
        -0.19766867,  0.72088892, -0.27304322, -0.89170678, -2.18684123,
         1.55695327,  0.09894319, -0.45222442, -0.91090876],
       [-1.10131326,  0.72679666,  0.60866562, -1.00396207, -0.7150907 ,
        -0.01723373, -0.18755455, -1.20682856,  0.59301323,  0.53335276,
        -0.40010804, -1.87649249, -0.97680874, -0.59682431,  0.33863299,
         1.13020513, -0.55029242, -0.47876527, -0.91294364, -1.

In [20]:
arr2 = arr1.reshape(2, 7, 7) # 按原顺序恢复成原shape
arr2 - arr

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])