$$ loss = - \sum_{n=0}^{N} \mathbf{w}_n X_{n, t}$$

In [24]:
import torch
import torch.nn.functional as F
import torch.nn as nn

In [25]:
a = torch.arange(24, dtype=torch.float32).reshape(4, 6)
a

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]])

In [26]:
true_index = torch.tensor([2, 1, 4, 0])
F.nll_loss(a, true_index)

tensor(-10.7500)

In [27]:
## 上式计算步骤如下
weight = torch.ones_like(true_index, dtype=torch.float32) / true_index.numel() # 样本权重
weight

tensor([0.2500, 0.2500, 0.2500, 0.2500])

In [28]:
step1 = a[[0, 1, 2, 3], true_index] # 即a[0, 1], a[1, 1], a[2, 4], a[3, 0]
step1

tensor([ 2.,  7., 16., 18.])

In [29]:
step2 = step1 * weight
step2

tensor([0.5000, 1.7500, 4.0000, 4.5000])

In [30]:
step3 = -torch.sum(step2)
step3

tensor(-10.7500)

In [31]:
nn.NLLLoss()(a, true_index)

tensor(-10.7500)