In [5]:
import torch

In [6]:
a = torch.tensor([10., 5., 2., 3.], requires_grad=True)
print(a, a.is_leaf)
print(id(a))

a = a + torch.tensor([4., 3., 2., 1.]) # 修改a
print(a, a.is_leaf) # ★★★★★a不再为叶tensor
print(id(a)) # a内存地址改变

loss = (a*a).mean()
print(loss)
loss.backward()
print(a.grad) # 输出None

tensor([10.,  5.,  2.,  3.], requires_grad=True) True
2832305579096
tensor([14.,  8.,  4.,  4.], grad_fn=<AddBackward0>) False
2832305580856
tensor(73., grad_fn=<MeanBackward0>)
None


## 解决:torch.no_grad()

In [7]:
a = torch.tensor([10., 5., 2., 3.], requires_grad=True)
print(a, a.is_leaf)
print(id(a))

with torch.no_grad():
    """Context-manager that disabled gradient calculation"""
    a[:] = torch.tensor([4., 3., 2., 1.]) # ★★★★★不能改变a内存地址(若a内存地址被改变,则a.grad=None)
print(a, a.is_leaf)
print(id(a))

loss = (a*a).mean()
loss.backward()
print(a.grad)

tensor([10.,  5.,  2.,  3.], requires_grad=True) True
2832305608648
tensor([4., 3., 2., 1.], requires_grad=True) True
2832305608648
tensor([2.0000, 1.5000, 1.0000, 0.5000])


## 解决:tor.data

In [8]:
a = torch.tensor([10., 5., 2., 3.], requires_grad=True)
print(a, a.is_leaf)
print(id(a))

a.data = torch.tensor([4., 3., 2., 1.]) # 只是修改a的值
print(a, a.is_leaf)
print(id(a)) # a内存地址不变

loss = (a*a).mean()
loss.backward()
print(a.grad)

tensor([10.,  5.,  2.,  3.], requires_grad=True) True
2832305579576
tensor([4., 3., 2., 1.], requires_grad=True) True
2832305579576
tensor([2.0000, 1.5000, 1.0000, 0.5000])
