In [1]:
import torch

In [2]:
a = torch.tensor([10., 5., 2., 3.], requires_grad=True)
print(a, a.is_leaf)
print(id(a))

a = a.reshape(-1, 1) # 修改a
print(a, a.is_leaf) # ★★★★★a不再为叶tensor
print(id(a)) # a内存地址改变

loss = (a*a).mean()
print(loss)
loss.backward()
print(a.grad) # 输出none

tensor([10.,  5.,  2.,  3.], requires_grad=True) True
2389004125912
tensor([[10.],
        [ 5.],
        [ 2.],
        [ 3.]], grad_fn=<ViewBackward>) False
2389004126872
tensor(34.5000, grad_fn=<MeanBackward0>)
None


## 解决tor.data

In [3]:
a = torch.tensor([10., 5., 2., 3.], requires_grad=True)
print(a, a.is_leaf)
print(id(a))

with torch.no_grad():
    """Context-manager that disabled gradient calculation"""
    a.data = a.data.reshape(-1, 1) # ★★★★★不能改变a内存地址(若a内存地址被改变,则a.grad=None)
print(a, a.is_leaf)
print(id(a))

loss = (a*a).mean()
loss.backward()
print(a.grad)

tensor([10.,  5.,  2.,  3.], requires_grad=True) True
2389004125352
tensor([[10.],
        [ 5.],
        [ 2.],
        [ 3.]], requires_grad=True) True
2389004125352
tensor([[5.0000],
        [2.5000],
        [1.0000],
        [1.5000]])


## 间接解决:tor.requires_grad_(True)

In [4]:
a = torch.tensor([10., 5., 2., 3.])
a = a.reshape(-1, 1)
a.requires_grad_(True)

loss = (a*a).mean()
print(loss)
loss.backward()
print(a.grad) # 输出none


tensor(34.5000, grad_fn=<MeanBackward0>)
tensor([[5.0000],
        [2.5000],
        [1.0000],
        [1.5000]])
