In [4]:
import torch

In [5]:
a = torch.tensor([10., 5., 2., 3.], requires_grad=True)
print(a, a.is_leaf)
print(id(a))

a[:] = torch.tensor([4., 3., 2., 1.]) # 修改a
print(a, a.is_leaf) # ★★★★★a不再为叶tensor
print(id(a)) # a内存地址不变

loss = (a*a).mean()
# 报错,a leaf Variable that requires grad has been used in an in-place operation.
loss.backward()
print(a.grad)

tensor([10.,  5.,  2.,  3.], requires_grad=True) True
2376486046520
tensor([4., 3., 2., 1.], grad_fn=<CopySlices>) False
2376486046520


RuntimeError: leaf variable has been moved into the graph interior

## 解决:torch.no_grad()

In [ ]:

a = torch.tensor([10., 5., 2., 3.], requires_grad=True)
print(a, a.is_leaf)
print(id(a))

with torch.no_grad():
    """Context-manager that disabled gradient calculation"""
    a[:] = torch.tensor([4., 3., 2., 1.]) # ★★★★★不能改变a内存地址(若a内存地址改变,则a.grad=None)
print(a, a.is_leaf)
print(id(a))

loss = (a*a).mean()
loss.backward()
print(a.grad)

## 解决:tor.data

In [7]:
a = torch.tensor([10., 5., 2., 3.], requires_grad=True)
print(a, a.is_leaf)
print(id(a))

a.data = torch.tensor([4., 3., 2., 1.]) # 只是修改a的值
print(a, a.is_leaf)
print(id(a)) # a内存地址不变

loss = (a*a).mean()
loss.backward()
print(a.grad)

tensor([10.,  5.,  2.,  3.], requires_grad=True) True
2376508528344
tensor([4., 3., 2., 1.], requires_grad=True) True
2376508528344
tensor([2.0000, 1.5000, 1.0000, 0.5000])
