$$ l_{n}=-w_{y_{n}} x_{n, y_{n}} $$

In [1]:
import torch
import torch.nn.functional as F

In [2]:
a = torch.arange(24, dtype=torch.float32).reshape(4, 6)
a

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]])

In [3]:
index = torch.tensor([2, 1, 4, 0])
F.nll_loss(a, index)

tensor(-10.7500)

In [4]:
## 上式计算步骤如下
weight = torch.ones_like(index, dtype=torch.float32) / index.numel() # 样本权重
weight

tensor([0.2500, 0.2500, 0.2500, 0.2500])

In [5]:
step1 = a[[0, 1, 2, 3], index] # 即a[0, 1], a[1, 1], a[2, 4], a[3, 0]
step1

tensor([ 2.,  7., 16., 18.])

In [6]:
step2 = step1 * weight
step2

tensor([0.5000, 1.7500, 4.0000, 4.5000])

In [7]:
step3 = -torch.sum(step2)
step3

tensor(-10.7500)