In [27]:
from sklearn import preprocessing

enc = preprocessing.OneHotEncoder()
X = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]
enc.fit(X)

OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)

In [28]:
enc.transform([['female', 'from US', 'uses Safari'],
               ['male', 'from Europe', 'uses Safari']]).toarray()

array([[1., 0., 0., 1., 0., 1.],
       [0., 1., 1., 0., 0., 1.]])

In [29]:
enc.categories_ # 默认情况下,从数据集中自动推断出来
# 解析
# female的编码是1, 0
# male的编码是0, 1
# from Europe的编码是1, 0
# from US的编码是0, 1
# users Firefox的编码是1, 0
# users Safari的编码是0, 1

[array(['female', 'male'], dtype=object),
 array(['from Europe', 'from US'], dtype=object),
 array(['uses Firefox', 'uses Safari'], dtype=object)]

In [30]:
genders = ['female', 'male']
locations = ['from Africa', 'from Asia', 'from Europe', 'from US']
browsers = ['uses Chrome', 'uses Firefox', 'uses IE', 'uses Safari']
enc1 = preprocessing.OneHotEncoder(categories=[genders, locations, browsers]) # 使用参数明确指定categories

In [31]:
X1 = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]
enc1.fit(X1)

OneHotEncoder(categorical_features=None,
              categories=[['female', 'male'],
                          ['from Africa', 'from Asia', 'from Europe',
                           'from US'],
                          ['uses Chrome', 'uses Firefox', 'uses IE',
                           'uses Safari']],
              drop=None, dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)

In [32]:
enc1.transform([['female', 'from US', 'uses Safari'],
               ['male', 'from Europe', 'uses Safari']]).toarray()

array([[1., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 0., 0., 1.]])

In [33]:
enc1.categories_
# 解析
# female的编码是1, 0
# male的编码是0, 1
# from Africal的编码是1, 0, 0, 0
# from Asia的编码是0, 1, 0, 0
# from Europe的编码是0, 0, 1, 0
# from US的编码是0, 0, 0, 1
# user Chrome的编码是1, 0, 0, 0
# users Firefox的编码是0, 1, 0, 0
# users IE的编码是0, 0, 1, 0
# users Safari的编码是0, 0, 0, 1

[array(['female', 'male'], dtype=object),
 array(['from Africa', 'from Asia', 'from Europe', 'from US'], dtype=object),
 array(['uses Chrome', 'uses Firefox', 'uses IE', 'uses Safari'],
       dtype=object)]

In [34]:
enc2 = preprocessing.OneHotEncoder(handle_unknown='ignore') # 如果训练数据有可能缺少分类特征,则通常最好指定handle_unknown='ignore',否则将报错
X2 = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]
enc2.fit(X)

enc2.transform([['female', 'from Asia', 'uses Chrome']]).toarray() # from Asia, uses Chrome训练数据中没有

array([[1., 0., 0., 0., 0., 0.]])

In [35]:
enc2.categories_

[array(['female', 'male'], dtype=object),
 array(['from Europe', 'from US'], dtype=object),
 array(['uses Firefox', 'uses Safari'], dtype=object)]