### 可变数据类型:list,dict,set,Series,DataFrame,ndarray,tensor
基本结构:
1. 包含指针地址与值地址,指针地址指向值地址,定义时变量的地址为指针地址
2. 变量赋值是将指针地址对其进行赋值


具体可参考:
1. list的修改与内存存储问题.ipynb
3. ndarray的存储结构.ipynb
3. array的修改与共享内存.ipynb
4. tensor的修改与共享内存.ipynb
5. 深拷贝浅拷贝copy模块

In [1]:
lst = [1, 2, 3, 4, 5]
lst1 = lst # lst,lst1指针地址相同

lst1.append(5)

print(lst)
print(lst1)

[1, 2, 3, 4, 5, 5]
[1, 2, 3, 4, 5, 5]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4])
arr1 = arr # arr,arr1指针地址相同

arr[0] = 1000

print(arr)
print(arr1)

[1000    2    3    4]
[1000    2    3    4]


In [8]:
import pandas as pd

df = pd.DataFrame([[1, 2], [3, 4]], index=['A', 'B'])
df1 = df # arr,arr1指针地址相同

df.iloc[0, 0] = 1000

print(df)
print(df1)

      0  1
A  1000  2
B     3  4
      0  1
A  1000  2
B     3  4


In [9]:
import torch

tor = torch.tensor([1, 2, 3, 4])
tor1 = tor # tor,tor1指针地址相同

tor[0] = -1

print(tor)
print(tor1)

tensor([-1,  2,  3,  4])
tensor([-1,  2,  3,  4])
