In [1]:
import  numpy as np
a = np.array([[1., 2.], [3., 4.]])
print(a.shape) # a是方阵
print(np.linalg.matrix_rank(a)) # a满秩
ainv = np.linalg.inv(a) # 故a可逆
print(ainv)
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
print(np.dot(a, ainv))

(2, 2)
2
[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 1.000  0.000]
 [ 0.000  1.000]]


In [4]:
b = np.array([[1, 2, 3], [4, 5, 6], [2, 4, 6]])
print(np.linalg.matrix_rank(b))
print(np.linalg.inv(b)) # 不可以逆

2


LinAlgError: Singular matrix

In [5]:
print(np.linalg.pinv(b)) # 计算广义逆矩阵

[[-0.189  0.444 -0.378]
 [-0.022  0.111 -0.044]
 [ 0.144 -0.222  0.289]]
